const MovieActionsTypes = {
  SET_MOVIE: "SET_MOVIE",
  FETCH_SUCCESS: "FETCH_SUCCESS",
  SET_PER_PAGE: "SET_PER_PAGE",
  SET_PER_PAGE_SUCCESS: "SET_PER_PAGE_SUCCESS",
  DELETE_MOVIE: "DELETE_MOVIE",
  SET_MOVIES_LIST: "SET_MOVIES_LIST",
  MOVIE_REACTION: "MOVIE_REACTION",
  SET_MOVIE_PER_PAGE: "SET_MOVIE_PER_PAGE",
  FILTER_BY_CATEGORY: "FILTER_BY_CATEGORY",
  FILTER_BY_CATEGORY_SUCCESS: "FILTER_BY_CATEGORY_SUCCESS",
  SET_CATEGORIES: "SET_CATEGORIES",
};

export default MovieActionsTypes;
